import { ArrowRight, Eye, MessageCircle, Repeat2 } from "lucide-react";
import { Link } from "wouter";
import { PublicLayout } from "@/components/PublicLayout";

const principles = [{ icon: Eye, title: "Observe", text: "Antes de tentar produzir tudo, você precisa perceber como a língua aparece em contexto." }, { icon: Repeat2, title: "Pratique", text: "Uma boa prática não ocupa a sua vida: ela encontra um lugar nela e volta com consistência." }, { icon: MessageCircle, title: "Use", text: "O uso real dá propósito ao que você aprendeu e revela o que merece mais atenção." }];

export default function Method() {
  return <PublicLayout><main><section className="mx-auto max-w-[1280px] px-5 py-20 lg:px-8 lg:py-28"><p className="eyebrow">Método</p><h1 className="font-editorial mt-6 max-w-4xl text-6xl leading-[.94] tracking-[-.03em] text-[#1F4D3A] lg:text-8xl">Aprender inglês é construir <span className="text-marker">autonomia</span>, não dependência.</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-[#557060]">O Learn to Learn English organiza a aprendizagem em experiências de compreensão, prática e uso. O objetivo é você saber como seguir evoluindo, dentro e fora da aula.</p></section><section className="border-y border-[#D7DDCF] bg-[#EEF1E8]"><div className="mx-auto grid max-w-[1280px] gap-7 px-5 py-16 lg:grid-cols-3 lg:px-8">{principles.map(({ icon: Icon, title, text }, index) => <article key={title} className="rounded-3xl bg-[#F8F4E8] p-7"><div className="flex items-center justify-between"><span className="font-editorial text-2xl text-[#1F4D3A]">0{index + 1}</span><span className="grid h-12 w-12 place-items-center rounded-full bg-[#E6D400] text-[#1F4D3A]"><Icon size={22} /></span></div><h2 className="font-editorial mt-12 text-4xl text-[#1F4D3A]">{title}</h2><p className="mt-4 text-sm leading-7 text-[#557060]">{text}</p></article>)}</div></section><section className="mx-auto grid max-w-[1280px] gap-10 px-5 py-24 lg:grid-cols-[.9fr_1.1fr] lg:px-8"><aside className="rounded-[2rem] bg-[#1F4D3A] p-9 text-[#F8F4E8]"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#E6D400]">Uma nova referência</p><p className="font-editorial mt-5 text-4xl leading-tight">Fluência não é falar sem errar. É conseguir comunicar o que importa.</p></aside><div><p className="eyebrow">Uma aprendizagem com sentido</p><h2 className="font-editorial mt-5 text-5xl leading-none text-[#1F4D3A]">Menos ansiedade, mais encontro com a língua.</h2><p className="mt-6 text-lg leading-8 text-[#557060]">Você não precisa esperar estar preparado para começar. A confiança é construída em pequenas tentativas, com repertório crescente e espaço para errar.</p><Link href="/como-funciona" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#1F4D3A] px-5 py-3 text-sm font-bold text-[#F8F4E8]">Ver como funciona <ArrowRight size={16} /></Link></div></section></main></PublicLayout>;
}
